name: Run Java Code

on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      filename:
        description: 'Path to the Java file to compile and run (e.g., Basics/HelloWorld.java)'
        required: true
        default: 'Basics/HelloWorld.java'

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Java
        run: sudo apt-get install -y default-jdk

      - name: Compile Java Code
        run: |
          cd $(dirname ${{ github.event.inputs.filename }}) # Navigate to the directory
          javac $(basename ${{ github.event.inputs.filename }}) # Compile the file

      - name: Run Java Program
        run: |
          cd $(dirname ${{ github.event.inputs.filename }}) # Navigate to the directory
          java $(basename ${{ github.event.inputs.filename }} .java) # Run the class file
