name: Run Java Code

on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      filename:
        description: 'Name of the Java file to compile and run'
        required: true
        default: 'Main.java'

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Java
        run: sudo apt-get install -y default-jdk

      - name: Compile Java Code
        run: javac ${{ github.event.inputs.filename }}

      - name: Run Java Program
        run: java ${{ github.event.inputs.filename }} # Strip .java manually
        env:
          filename: ${{ github.event.inputs.filename }}
